[package]
name = "exploring_graphics_programming"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "exploring_graphics_programming"
path = "src/main.rs"

[dependencies]
bytemuck = { version = "1.22.0", features = ["derive"] }
futures = "0.3.31"
wgpu = "24.0.3"
